appName: python:v1
namespace: 618857-deploymentapp

replicaCount: 1

image:
  repository: jnanasrikrishna/python
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

configmap:
  name: python-configmap-v1
  data:
    CUSTOM_HEADER: 'Welcome to the Python App!'