appName: python

namespace: 618857-deploymentapp

replicaCount: 1

image:
  repository: jnanasrikrishna/python
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

route:
  enabled: false
  host: python-app.example.com

resources: {}

persistence:
  enabled: false
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: ""

configmap:
  name: python-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

secrets: {}
