# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-python
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}-python
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-python
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-python
    spec:
      containers:
      - name: python
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        {{- if .Values.configmap }}
        - name: CUSTOM_HEADER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: CUSTOM_HEADER
        {{- end }}
